### PR TITLE
School redesign

### PR DESCRIPTION
**Pull request by sigilante**
This adds descriptions and mailing list submission for the next two cohort class offerings we are planning in 2023.

### CODE REVIEW

**Comment by sigilante** [comment]
@gordoncc I guess we'll want some little icons for those two new ones and a check on page layout (2×2 is fine).

**Comment by sigilante** [comment]
One question:  https://developers.urbit.org/courses  where do I add tiles to this page?

**Comment by matthew-levan** [comment]
> One question: https://developers.urbit.org/courses where do I add tiles to this page?

@sigilante `pages/courses.js` has a list of maps you could add Core School to (or what have you).

**Comment by gordoncc** [comment]
@sigilante Yeah, what Matthew said.  I intend refactor this so that we don't need to list the data in the courses.js and can pull in metadata from the .md files.

**Pull request merged**
