### PR TITLE
Rename guides

### PR DESCRIPTION
**Pull request by sigilante**
Rework the guide content into a better order with a more consistent and explanatory naming scheme.

### CODE REVIEW

**Comment by sigilante** [comment]
@gordoncc this will impact the tiles on the Guides page as well.

**Comment by matildepark** [comment]
I'm just gonna put a PR in to do it programmatically.

**Comment by sigilante** [comment]
Also Threads still doesn't sort between Strings and Unit Tests, not sure where it's picking up its weight.

**Comment by matildepark** [comment]
> Also Threads still doesn't sort between Strings and Unit Tests, not sure where it's picking up its weight.

It looks like it's a whole directory. I think directories always come before pages for the sorting.

**Review by gordoncc — APPROVED** [review]

**Pull request merged**
