### PR TITLE
OM Illustrations + New Dev Ed Terminology

### PR DESCRIPTION
**Pull request by gordoncc**
Updated all the card and icon illustrations and used new terminology across the site.

Redirects to old guide and course URLs should be handled.

OM may not be a fan of incrementally rolling out their design, but I feel like it's OK since we're starting to use the font a lot more publicly in other places.

### CODE REVIEW

**Comment by thomasurbit** [comment]
I think this is good, I added @jalehman as it's quite a change to the website. 

One thing I notice at /courses is that the dark background with blue icon for app workshop is a bit out of place. I don't know how we could solve that considering OM's colour scheme. Same goes for /guides. Also the tilted workbook looks a bit off from the rest. lmk what you all think.

**Review by thomasurbit — CHANGES_REQUESTED** [review]
see above, let's discuss it here first before merging.

**Comment by gordoncc** [comment]
@thomasurbit was able to lighten up the app workshop card a bit with one of OMs colors. 

the guide icons were a bit larger than the other ones.  another pass where they're the same size.

Screenshot 2023-04-24 at 3 23 45 PM

**Comment by thomasurbit** [comment]
Colours fit in better! I did prefer the use of the icon's.

**Comment by sigilante** [comment]
I may collapse all of the App Guide stuff together—can I get:

1. Hoon Workbook icon
2. App Workbook icon
3. Single App Guide icon

just to cover bases if I reorg that way?

**Comment by thomasurbit** [comment]
@sigilante what do you mean exactly?

**Comment by sigilante** [comment]
I would like to restructure the guides along these lines soon:

1. Environment Setup
2. Hoon Guide
3. App Guide (all stuff nested under)

which leaves a hanging spot for a fourth entry in the grid.

So another possibility is to pull up something like this and break the symmetry (five being better than three in that case):

1. Environment Setup
2. Hoon Guide
3. Hoon Workbook
4. App Guide (which will contain AG1/AG2)
5. App Workbook

or we could just go with three on this page like the first one.  What do you think?

**Comment by gordoncc** [comment]
@sigilante – don't worry at all about symmetry or layout when considering the structure of these guides.  Having the workbooks be a part of the guides makes sense to me though.

**Comment by gordoncc** [comment]
@sigilante put together some icons that you requested – please find attached.
App Workbook
Hoon Workbook
Single App Icon

**Pull request closed without merging**
