### PR TITLE
Add breach and factory reset to the glossary.

### PR DESCRIPTION
**Pull request by sigilante**

### CODE REVIEW

**Comment by sigilante** [comment]
It may be better to redirect instead of duplicate.

**Comment by matildepark** [comment]
You can just put both glossary entry TOMLs at the top of one of the pages to register two entries for the one page.

**Comment by tinnus-napbus** [comment]
there is already a factory reset entry: https://developers.urbit.org/reference/glossary/reset

**Comment by sigilante** [comment]
@tinnus-napbus ready for re-review now

**Pull request merged**
