### PR TITLE
Document some more Dojo features.

### PR DESCRIPTION
**Pull request by sigilante**
Include threads, Dojo session crashes, and `?` type inspection.

### CODE REVIEW

**Comment by matildepark** [comment]
Every other page in this section is a paragraph long, and the lack of a table of contents was put there to reflect that. Isn't this operator's content?

**Comment by sigilante** [comment]
Seems to me that how to run a thread, or what Hood is doing, or how to redirect output to a file are all developer concerns.

**Comment by matildepark** [comment]
I don't disagree. And I can see a bit of this precedes this PR, so out of scope ... I can just see someone being confused since there isn't a table of contents.

**Comment by sigilante** [comment]
If we split it, what goes where?

From the d.u.o. side, there's not really a good other place unless we just wedge in an Additional Guide or Dojo reference—but this isn't really a reference, so much.

**Comment by gordoncc** [comment]
> If we split it, what goes where?
> 
> From the d.u.o. side, there's not really a good other place unless we just wedge in an Additional Guide or Dojo reference—but this isn't really a reference, so much.

It seems like Quickstart, Math, System Commands, and Generators all belong in a Dojo Guide under Additional Guides.

The Dojo manual seems like it could live under the Dojo Guide or under References / Dojo. 

Either way, this page is definitely much bigger than an overview and should be broken out as such with TOC links to the respective guide or reference sections.

**Comment by tinnus-napbus** [comment]
all of this kind of thing should go in operators imo

**Comment by matildepark** [comment]
@tinnus-napbus to break this content out into operator's.

**Comment by sigilante** [comment]
@tinnus-napbus is this superseded by your new guide?

**Review by gordoncc — APPROVED** [review]

**Comment by sigilante** [comment]
This is the main part we need to put somewhere in some form:

#### Inspecting Values

You can prefix a value in the Dojo with `?` to inspect its type in some
way.

- `?` gives the type as printed by `hoon.hoon`.
- `??` shows the type noun as-is.
- `???` shows the `hoon` of the expression.
- `????` reveals the `spec` of a gate.
- `?????` uses an “x-ray” pretty-printer.

```hoon
> ? `@da`(add ~2000.1.1 ~d366)
  @da
~2001.1.1
> ?? `@da`(add ~2000.1.1 ~d366)
  [%atom %da ~]
~2001.1.1
> ??? `@da`(add ~2000.1.1 ~d366)
[ %ktls
  p=[%sand p=%da q=0]
    q
  [ %ktls
    p=[%sand p=%$ q=0]
      q
    [ %cncl
      p=[%wing p=~[%add]]
        q
      ~[
        [%sand p=%da q=170.141.184.492.615.420.181.573.981.275.213.004.800]
        [%sand p=%dr q=583.330.319.796.472.925.021.798.400]
      ]
    ]
  ]
]
> ???? add
$-([a=@ b=@] @)
> ????? `@da`(add ~2000.1.1 ~d366)
  @da
~2001.1.1
```

### Troubleshooting

#### `%dojo-peer-replaced`/`%drum-coup-fail`

If you carry out a command that crashes the Dojo session (such as a bad
scry), Dojo will automatically restart itself with a clean new session.
You will lose some Dojo state, such as variables pinned with `=` or
files built with `-build-thread`.

#### `%dy-edit-busy`

If you encounter `%dy-edit-busy` while entering commands, it is
because your Dojo is blocked on a timer or an HTTP request. Type backspace
and your Dojo will end the blocked command.

**Comment by tinnus-napbus** [comment]
> @tinnus-napbus is this superseded by your new guide?

No. I was intending to get the whole doc out of developers and into operators. I documented all the generators and threads in the %base desk but then I got sucked into other things. We should just merge this in the meantime, when I get around to rewriting the shell/dojo guide in the user manual I will see about deprecating this doc

**Review by tinnus-napbus — APPROVED** [review]

**Pull request merged**
