### PR TITLE
docs(glossary/sponsor.md): add an explanation in the glossary as to w…

### PR DESCRIPTION
**Pull request by netpoetica**
…hat a sponsor is

as explained to me by ~monted-tallex in Urbit Community -> General

### CODE REVIEW

**Comment by netpoetica** [comment]
Confirmed proper rendering here: https://developers-urbit-28tbs4frt-urbit.vercel.app/reference/glossary/sponsor

**Comment by sigilante** [comment]
(also, thanks for doing this)

**Comment by matildepark** [comment]
I don’t know; aren’t peers any other ship? A hierarchical peer system still characterises sponsors as peers but with a different relation to you.

**Comment by sigilante** [comment]
That is the way the docs use it, yes, so let's roll with it.

**Pull request merged**
