### PR TITLE
hoon school edits & irregular syntax edits/additions

### PR DESCRIPTION
**Pull request by nogira**
this PR (commit https://github.com/urbit/developers.urbit.org/pull/163/commits/ad6b585d4e00d39cf4c0e35d28c5def81a96e5e1) should close this issue https://github.com/urbit/developers.urbit.org/issues/144

(also a prev merged PR https://github.com/urbit/developers.urbit.org/pull/155 (commit https://github.com/urbit/developers.urbit.org/pull/155/commits/87f47c219c026663ffd5acd0b7e53e860350adec (though spelling turned out not to be an error)) fixed the stuff in this unmerged PR https://github.com/urbit/developers.urbit.org/pull/76, so that can prob be closed too)

### CODE REVIEW

**Comment by nogira** [comment]
regarding the above commit, the whole dot rune type-check section got removed in a prior commit, but only the dottis part doesn't do a type-check. dotlus still seems to type-check

**Comment by nogira** [comment]
is it safe to convert `{% customFence %}` to a code block? none of them render as code blocks (example [here](https://developers.urbit.org/reference/arvo/clay/scry#d---list-desks)), and changing one of them to a code block seemed to be fine (despite the code containing a `{%` in it). if the `{%`s in the code do have an effect, one solution is to just replace those `%`s with a different unicode version of percent such as `﹪`; it's barely noticeable, and since it's dojo output, not input, it is unlikely to be copied by users to try to use

**Comment by matildepark** [comment]
I think I removed the customFence component or something because it wasn't necessary. Wasn't aware there were still some here. Yes, it was fixed in Markdoc 0.13 or something.

**Comment by matildepark** [comment]
@nogira Mind re-merging main back into yours?

**Review by sigilante — APPROVED** [review]

**Comment by nogira** [comment]
@matildepark done :)

**Pull request merged**
