### PR TITLE
Refactor/specify node engine version

### PR DESCRIPTION
**Pull request by netpoetica**
Fixes https://github.com/urbit/developers.urbit.org/issues/235

I used 14.17 here because the package-lock was using v2 of package-lock, so you need a specific version of node 14 that is compat w/ npm version that uses v2. The ones mentioned in here are appropriate combination of v14.17 + npm that supports package-lock v2.

### CODE REVIEW

**Comment by sigilante** [comment]
@tinnus-napbus what about the package.json and lock files in this PR?

**Comment by tinnus-napbus** [comment]
I don't know about node version stuff sorry

**Comment by netpoetica** [comment]
@sigilante Those lock files are supposed to be in there - this allows other JS devs to ensure they are using the same versions. Otherwise different versions of node, npm, yarn or example may interpret package.json version resolutions differently.

**Comment by sigilante** [comment]
In that case, let's merge it.

It works fine for me to build and host locally.

**Pull request merged**
